### ISSUE TITLE
Does not compile on Ubuntu 16.04 x64 + gcc version 5.4.0

### ISSUE THREAD

**Issue by TjWallas** [zevv/bucklespring#4]
As of commit ID:
* a002853 (HEAD -> master, origin/master, origin/HEAD) Link win32 with -static-libgcc -static-libstdc++

Just tried to follow the instructions in the readme and compile it but, make failed:
```
❯ make                                                                                                                                                                                                                          
g++ -g -lalure -lopenal -lXtst -lX11 -o buckle  main.o scan-linux.o scan-windows.o 
main.o: In function `play':
/tmp/bucklespring/main.c:255: undefined reference to `alSourcePlay'
/tmp/bucklespring/main.c:256: undefined reference to `alGetError'
/tmp/bucklespring/main.c:235: undefined reference to `alureCreateBufferFromFile'
/tmp/bucklespring/main.c:242: undefined reference to `alGenSources'
/tmp/bucklespring/main.c:243: undefined reference to `alGetError'
/tmp/bucklespring/main.c:246: undefined reference to `alSource3f'
/tmp/bucklespring/main.c:247: undefined reference to `alSourcef'
/tmp/bucklespring/main.c:249: undefined reference to `alSourcei'
/tmp/bucklespring/main.c:250: undefined reference to `alGetError'
/tmp/bucklespring/main.c:237: undefined reference to `alureGetErrorString'
main.o: In function `list_devices':
/tmp/bucklespring/main.c:159: undefined reference to `alcGetString'
main.o: In function `main':
/tmp/bucklespring/main.c:109: undefined reference to `alcOpenDevice'
/tmp/bucklespring/main.c:116: undefined reference to `alcCreateContext'
/tmp/bucklespring/main.c:117: undefined reference to `alcMakeContextCurrent'
/tmp/bucklespring/main.c:121: undefined reference to `alGetError'
/tmp/bucklespring/main.c:123: undefined reference to `alListener3f'
/tmp/bucklespring/main.c:124: undefined reference to `alListener3f'
/tmp/bucklespring/main.c:125: undefined reference to `alListenerfv'
/tmp/bucklespring/main.c:130: undefined reference to `alcGetContextsDevice'
/tmp/bucklespring/main.c:131: undefined reference to `alcMakeContextCurrent'
/tmp/bucklespring/main.c:132: undefined reference to `alcDestroyContext'
/tmp/bucklespring/main.c:133: undefined reference to `alcCloseDevice'
/tmp/bucklespring/main.c:130: undefined reference to `alcGetContextsDevice'
/tmp/bucklespring/main.c:131: undefined reference to `alcMakeContextCurrent'
/tmp/bucklespring/main.c:104: undefined reference to `alcGetString'
scan-linux.o: In function `scan':
/tmp/bucklespring/scan-linux.c:23: undefined reference to `XOpenDisplay'
/tmp/bucklespring/scan-linux.c:29: undefined reference to `XRecordAllocRange'
/tmp/bucklespring/scan-linux.c:39: undefined reference to `XRecordCreateContext'
/tmp/bucklespring/scan-linux.c:45: undefined reference to `XFree'
/tmp/bucklespring/scan-linux.c:47: undefined reference to `XRecordEnableContext'
scan-linux.o: In function `key_pressed_cb':
/tmp/bucklespring/scan-linux.c:87: undefined reference to `XRecordFreeData'
/tmp/bucklespring/scan-linux.c:87: undefined reference to `XRecordFreeData'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'buckle' failed
make: *** [buckle] Error 1
```

OS:
Ubuntu 16.04.1 LTS x64

GCC:
```
❯ g++ -v                                                                                                                                                                                                                         
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
```

Libraries:
```
❯ sudo aptitude show libopenal-dev libalure-dev libxtst-dev                                                                                                                                                                     
Package: libopenal-dev                   
State: installed
Automatically installed: no
Multi-Arch: same
Version: 1:1.16.0-3
Priority: optional
Section: universe/libdevel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 181 k
Depends: libopenal1 (= 1:1.16.0-3)
Breaks: libopenal-dev:i386 (!= 1:1.16.0-3)
Replaces: libopenal-dev:i386 (< 1:1.16.0-3)
Description: Software implementation of the OpenAL audio API (development files)
 OpenAL, the Open Audio Library, is a joint effort to create an open, vendor-neutral, cross-platform API for interactive, primarily spatialized audio. OpenAL's primary audience are application developers and desktop users that rely on
 portable standards like OpenGL, for games and other multimedia applications. 
 
 This package contains the files necessary for development with OpenAL .
Homepage: http://kcat.strangesoft.net/openal.html


Package: libalure-dev
State: installed
Automatically installed: no
Multi-Arch: same
Version: 1.2-6
Priority: optional
Section: universe/libdevel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 430 k
Depends: libopenal-dev, libalure1 (= 1.2-6)
Suggests: alure-doc
Breaks: libalure-dev:i386 (!= 1.2-6)
Replaces: libalure-dev:i386 (< 1.2-6)
Description: AL Utilities REtooled (development files)
 ALURE is a utility library to help manage common tasks with OpenAL applications. This includes device enumeration and initialization, file loading, and streaming. 
 
 The purpose of this library is to provide pre-made functionality that would otherwise be repetitive or difficult to (re)code for various projects and platforms, such as loading a sound file into an OpenAL buffer and streaming an audio
 file through a buffer queue. Support for different formats is consistant across platforms, so no special checks are needed when loading files, and all formats are handled through the same API. 
 
 Currently ALURE includes a basic .wav and .aif file reader, and can leverage external libraries such as libSndFile (for extended wave formats and several others), VorbisFile (for Ogg Vorbis), and FLAC (for FLAC and Ogg FLAC), and others.
 External libraries can also be dynamically loaded at run-time, or individually disabled outright at compile time. 
 
 This package contains the files necessary for development.
Homepage: http://kcat.strangesoft.net/alure.html


Package: libxtst-dev
State: installed
Automatically installed: no
Multi-Arch: same
Version: 2:1.2.2-1
Priority: optional
Section: libdevel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 103 k
Depends: libxtst6 (= 2:1.2.2-1), libx11-dev, libxext-dev, libxi-dev, x11proto-xext-dev (>= 7.0.99.3), x11proto-record-dev (>= 1.13.99.1)
Breaks: libxtst-dev:i386 (!= 2:1.2.2-1)
Replaces: x11proto-record-dev (< 1.13.99.1), x11proto-xext-dev (< 7.0.99.3), x11proto-xext-dev:i386 (< 7.0.99.3), x11proto-record-dev:i386 (< 1.13.99.1), libxtst-dev:i386 (< 2:1.2.2-1)
Description: X11 Record extension library (development headers)
 libXtst provides an X Window System client interface to the Record extension to the X protocol. 
 
 The Record extension allows X clients to synthesise input events, which is useful for automated testing. 
 
 This package contains the development headers for the library found in libxtst6.  Non-developers likely have little use for this package. 
 
 More information about X.Org can be found at: <URL:http://www.X.org> 
 
 This module can be found at git://anongit.freedesktop.org/git/xorg/lib/libXtst

```

**Comment by zevv** [comment]
fix for this has just been pulled, linker arguments order was broken
